language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home zx
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

script: "./gradlew clean build"

#CI 실행 ㅗ안료시 메일로 알람
notifications:
  email:
    recipients:
      - lts0424@naver.com
