language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

before_install:
  - chmod +x gradlew
script: "./gradlew clean build"

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build2
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main #해당 라인 추가

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-build2 #S3 버킷
    key: freelec-springboot2-webservice.zip# 빌드 파일을 압축해서 전달

    bundle_type: zip # 압축 확장자
    application: springboot2-webservice #웹 콘솔에서 등록한 Codedeploy어플리케이션

    deployment_group: springboot2-webservice-group

    region: ap-northeast-2
    wait_until-deployed: true
    on:
      branch: main #해당 라인 추가

#CI 실행 ㅗ안료시 메일로 알람
notifications:
  email:
    recipients:
      - lts0424@naver.com

